### ISSUE TITLE
Godaddy fail with 3.4.3 when creating TXT record

### ISSUE THREAD

**Issue by forouher** [AnalogJ/lexicon#603]
Hi, I'm currently unable to create new records with lexicon at Godaddy.
(noticed via dnsrobocert)

Steps to reproduce:

$ pip3 install dns-lexicon
$ lexicon --version
lexicon 3.4.3
$ lexicon godaddy list mydomain.eu TXT
[...] // works correctly
$ lexicon godaddy create mydomain.eu TXT --name=foo --content=bar
Traceback (most recent call last):
  File "/home/dariush/.local/bin/lexicon", line 8, in <module>
    sys.exit(main())
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/cli.py", line 124, in main
    results = client.execute()
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/client.py", line 88, in execute
    return self.provider.create_record(record_type, name, content)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/base.py", line 87, in create_record
    return self._create_record(rtype, name, content)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 119, in _create_record
    self._put("/domains/{0}/records".format(domain), records)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/base.py", line 165, in _put
    return self._request("PUT", url, data=data, query_params=query_params)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 317, in _request
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/forouher.eu/records

**Comment by adferrand** [comment]
This is fixed in 3.4.4.

**Comment by forouher** [comment]
Hi,

thanks for looking into this!

Unfortunately, the issue persists:

$ lexicon --version
lexicon 3.4.4
$ lexicon godaddy create XXX.eu TXT --name=foo6 --content=bar --auth-key xxx --auth-secret YYY 
Traceback (most recent call last):
  File "/home/dariush/.local/bin/lexicon", line 8, in <module>
    sys.exit(main())
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/cli.py", line 124, in main
    results = client.execute()
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/client.py", line 88, in execute
    return self.provider.create_record(record_type, name, content)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/base.py", line 87, in create_record
    return self._create_record(rtype, name, content)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 119, in _create_record
    self._put("/domains/{0}/records".format(domain), records)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/base.py", line 165, in _put
    return self._request("PUT", url, data=data, query_params=query_params)
  File "/home/dariush/.local/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 317, in _request
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/XXX.eu/records

**Comment by forouher** [comment]
Note: #545 also fixes this issue (although my domain doesn't have any CAA records).

**Comment by forouher** [comment]
Okay, it works again. Even with version 3.4.4. Seems like Godaddy fixed the API on their side. 

Closing this MR, thanks!
